exports.name = 'DG1'

exports.fields = [
    'SegmentType'
  , 'SetID'
  , 'DiagnosisCodingMethod'
  , 'DiagnosisCode'
  , 'DiagnosisDescription'
  , 'DiagnosisDateTime'
  , 'DiagnosisType'
  , 'MajorDiagnosticCategory'
  , 'DiagnosticRelatedGroup'
  , 'DRGApprovalIndicator'
  , 'DRGGrouperReviewCode'
  , 'OutlierType'
  , 'OutlierDays'
  , 'OutlierCost'
  , 'GrouperVersionAndType'
  , 'DiagnosisPriority'
  , 'DiagnosingClinician'
  , 'DiagnosisClassification'
  , 'ConfidentialIndicator'
  , 'AttestationDateTime'
]
