'use strict'

exports.name = 'FT1'

exports.fields = [
    'SegmentType'
  , 'SetIDFT1'
  , 'TransactionID'
  , 'TransactionBatchID'
  , 'TransactionDate'
  , 'TransactionPostingDate'
  , 'TransactionType'
  , 'TransactionCode'
  , 'TransactionDescription'
  , 'TransactionDescriptionAlt'
  , 'TransactionQuantity'
  , 'TransactionAmountExtended'
  , 'TransactionAmountUnit'
  , 'DepartmentCode'
  , 'InsurancePlanID'
  , 'InsuranceAmount'
  , 'AssignedPatientLocation'
  , 'FeeSchedule'
  , 'PatientType'
  , 'DiagnosisCodeFT1'
  , 'PerformedByCode'
  , 'OrderedByCode'
  , 'UnitCost'
  , 'FillerOrderNumber'
  , 'EnteredByCode'
  , 'ProcedureCode'
  , 'ProcedureCodeModifier'
]
