'use strict'

exports.name = 'GT1'

exports.fields = [
    'SegmentType'
  , 'SetID'
  , 'GuarantorNumber'
  , 'GuarantorName'
  , 'GuarantorSpouseName'
  , 'GuarantorAddress'
  , 'GuarantorPhoneHome'
  , 'GuarantorPhoneBusiness'
  , 'GuarantorBirthDate'
  , 'GuarantorSex'
  , 'GuarantorType'
  , 'GuarantorRelationship'
  , 'GuarantorSSN'
  , 'GuarantorDateBegin'
  , 'GuarantorDateEnd'
  , 'GuarantorPriority'
  , 'GuarantorEmployerName'
  , 'GuarantorEmployerAddress'
  , 'GuarantorEmployerPhoneNumber'
  , 'GuarantorEmployeeIDNumber'
  , 'GuarantorEmploymentStatus'
  , 'GuarantorOrganizationName'
  , 'GuarantorBillingHoldFlag'
  , 'GuarantorCreditRatingCode'
  , 'GuarantorDeathDateTime'
  , 'GuarantorDeathFlag'
  , 'GuarantorChargeAdjustmentCode'
  , 'GuarantorHouseholdAnnualIncome'
  , 'GuarantorHouseholdSize'
  , 'GuarantorEmployerIDNumber'
  , 'GuarantorMaritalStatusCode'
  , 'GuarantorHireEffectiveDate'
  , 'EmploymentStopDate'
  , 'LivingDependency'
  , 'AmbulatoryStatus'
  , 'Citizenship'
  , 'PrimaryLanguage'
  , 'LivingArrangement'
  , 'PublicityCode'
  , 'ProtectionIndicator'
  , 'StudentIndicator'
  , 'Religion'
  , 'MothersMaidenName'
  , 'Nationality'
  , 'EthnicGroup'
  , 'ContactPersonsName'
  , 'ContactPersonsTelephoneNumber'
  , 'ContactReason'
  , 'ContactRelationship'
  , 'JobTitle'
  , 'JobCodeClass'
  , 'GuarantorEmployersOrganizationName'
  , 'Handicap'
  , 'JobStatus'
  , 'GuarantorFinancialClass'
  , 'GuarantorRace'
]
