exports.name = 'IN1'

exports.fields = [
    'SegmentType'
  , 'SetID'
  , 'InsurancePlanID'
  , 'InsuranceCompanyID'
  , 'InsuranceCompanyName'
  , 'InsuranceCompanyAddress'
  , 'InsuranceCoContactPerson'
  , 'InsuranceCoPhoneNumber'
  , 'GroupNumber'
  , 'GroupName'
  , 'InsuredsGroupEmpID'
  , 'InsuredsGroupEmpName'
  , 'PlanEffectiveDate'
  , 'PlanExpirationDate'
  , 'AuthorizationInformation'
  , 'PlanType'
  , 'NameOfInsured'
  , 'InsuredsRelationshipToPatient'
  , 'InsuredsDateOfBirth'
  , 'InsuredsAddress'
  , 'AssignmentOfBenefits'
  , 'CoordinationOfBenefits'
  , 'CoordOfBenPriority'
  , 'NoticeOfAdmissionFlag'
  , 'NoticeOfAdmissionDate'
  , 'ReportOfEligibilityFlag'
  , 'ReportOfEligibilityDate'
  , 'ReleaseInformationCode'
  , 'PreAdmitCert'
  , 'VerificationDateTime'
  , 'VerificationBy'
  , 'TypeOfAgreementCode'
  , 'BillingStatus'
  , 'LifetimeReserveDays'
  , 'DelayBeforeLRDay'
  , 'CompanyPlanCode'
  , 'PolicyNumber'
  , 'PolicyDeductible'
  , 'PolicyLimitAmount'
  , 'PolicyLimitDays'
  , 'RoomRateSemiPrivate'
  , 'RoomRatePrivate'
  , 'InsuredsEmploymentStatus'
  , 'InsuredsSex'
  , 'InsuredsEmployersAddress'
  , 'VerificationStatus'
  , 'PriorInsurancePlanID'
  , 'CoverageType'
  , 'Handicap'
  , 'InsuredsIDNumber'
]
