//
// IN2 Segment Definition
//
// Author:    Evan Lucas
// Filename:  segment.js
// Created:   2/6/14
// Copyright: Evan Lucas 2014
//
exports.name = 'IN2'

exports.fields = [
    'SegmentType'
  , 'InsuredsEmployeeID'
  , 'InsuredsSocialSecurityNumber'
  , 'InsuredsEmployersNameandID'
  , 'EmployerInformationData'
  , 'MailClaimParty'
  , 'MedicareHealthInsCardNumber'
  , 'MedicaidCaseName'
  , 'MedicaidCaseNumber'
  , 'MilitarySponsorName'
  , 'MilitaryIDNumber'
  , 'DependentOfMilitaryRecipient'
  , 'MilitaryOrganization'
  , 'MilitaryStation'
  , 'MilitaryService'
  , 'MilitaryRankGrade'
  , 'MilitaryStatus'
  , 'MilitaryRetireDate'
  , 'MilitaryNonAvailCertOnFile'
  , 'BabyCoverage'
  , 'CombineBabyBill'
  , 'BloodDeductible'
  , 'SpecialCoverageApprovalName'
  , 'SpecialCoverageApprovalTitle'
  , 'NonCoveredInsuranceCode'
  , 'PayorID'
  , 'PayorSubscriberID'
  , 'EligibilitySource'
  , 'RoomCoverageTypeAmount'
  , 'PolicyTypeAmount'
  , 'DailyDeductible'
  , 'LivingDependency'
  , 'AmbulatoryStatus'
  , 'Citizenship'
  , 'PrimaryLanguage'
  , 'LivingArrangement'
  , 'PublicityCode'
  , 'ProtectionIndicator'
  , 'StudentIndicator'
  , 'Religion'
  , 'MothersMaidenName'
  , 'Nationality'
  , 'EthnicGroup'
  , 'MaritalStatus'
  , 'InsuredsEmploymentStartDate'
  , 'EmploymentStopDate'
  , 'JobTitle'
  , 'JobCodeClass'
  , 'JobStatus'
  , 'EmployerContactPersonName'
  , 'EmployerContactPersonPhoneNumber'
  , 'EmployerContactReason'
  , 'InsuredsContactPersonsName'
  , 'InsuredsContactPersonPhoneNumber'
  , 'InsuredsContactPersonReason'
  , 'RelationshipToThePatientStartDate'
  , 'RelationshipToThePatientStopDate'
  , 'InsuranceCoContactReason'
  , 'InsuranceCoContactPhoneNumber'
  , 'PolicyScope'
  , 'PolicySource'
  , 'PatientMemberNumber'
  , 'GuarantorsRelationshipToInsured'
  , 'InsuredsPhoneNumberHome'
  , 'InsuredsEmployerPhoneNumber'
  , 'MilitaryHandicappedProgram'
  , 'SuspendFlag'
  , 'CopayLimitFlag'
  , 'StoplossLimitFlag'
  , 'InsuredOrganizationNameAndID'
  , 'InsuredEmployerOrganizationNameAndID'
  , 'Race'
  , 'HCFAPatientsRelationshiptoInsured'
]
