exports.name = 'MSH'

exports.fields = [
    'SegmentType'
  , 'EncodingCharacters'
  , 'SendingApplication'
  , 'SendingFacility'
  , 'ReceivingApplication'
  , 'ReceivingFacility'
  , 'DateTime'
  , 'Security'
  , 'MessageType'
  , 'MessageControlID'
  , 'ProcessingID'
  , 'VersionID'
  , 'SequenceNumber'
  , 'ContinuationPointer'
  , 'AcceptAcknowledgementType'
  , 'ApplicationAcknowledgementType'
  , 'CountryCode'
  , 'CharacterSet'
  , 'PrincipalLanguage'
  , 'AlternateCharacterSetHandlingScheme'
]

