exports.name = 'NK1'

exports.fields = [
    'SegmentType'
  , 'SetID'
  , 'Name'
  , 'Relationship'
  , 'Address'
  , 'PhoneNumber'
  , 'BusinessPhoneNumber'
  , 'ContactRole'
  , 'StartDate'
  , 'EndDate'
  , 'NextOfKinJobTitle'
  , 'NextOfKinJobCodeClass'
  , 'NextOfKinEmployeeNumber'
  , 'OrganizationName'
  , 'MaritalStatus'
  , 'Sex'
  , 'BirthDate'
  , 'LivingDependency'
  , 'AmbulatoryStatus'
  , 'Citizenship'
  , 'PrimaryLanguage'
  , 'LivingArrangement'
  , 'PublicityCode'
  , 'ProtectionIndicator'
  , 'StudentIndicator'
  , 'Religion'
  , 'MotherMaidenName'
  , 'Nationality'
  , 'EthnicGroup'
  , 'ContactReason'
  , 'ContactPersonName'
  , 'ContactPersonPhoneNumber'
  , 'ContactPersonAddress'
  , 'NextOfKinIdentifiers'
  , 'JobStatus'
  , 'Race'
  , 'Handicap'
  , 'ContactPersonSSN'
]

