'use strict'

exports.name = 'OBR'

exports.fields = [
    'SegmentType'
  , 'SetID'
  , 'PlacerOrderNumber'
  , 'FillerOrderNumber'
  , 'UniversalServiceID'
  , 'Priority'
  , 'RequestedDateTime'
  , 'ObservationDateTime'
  , 'ObservationEndDateTime'
  , 'CollectionVolume'
  , 'CollectorIdentifier'
  , 'SpecimenActionCode'
  , 'DangerCode'
  , 'RelevantClinicalInfo.'
  , 'SpecimenReceivedDateTime'
  , 'SpecimenSource'
  , 'OrderingProvider'
  , 'OrderCallbackPhoneNumber'
  , 'PlacerField1'
  , 'PlacerField2'
  , 'FillerField1'
  , 'FillerField2'
  , 'ResultsRptStatusChngDateTime'
  , 'ChargeToPractice'
  , 'DiagnosticServSectID'
  , 'ResultStatus'
  , 'ParentResult'
  , 'QuantityTiming'
  , 'ResultCopiesTo'
  , 'Parent'
  , 'TransportationMode'
  , 'ReasonForStudy'
  , 'PrincipalResultInterpreter'
  , 'AssistantResultInterpreter'
  , 'Technician'
  , 'Transcriptionist'
  , 'ScheduledDateTime'
  , 'NumberofSampleContainers'
  , 'TransportLogisticsOfCollectedSample'
  , 'CollectorsComment'
  , 'TransportArrangementResponsibility'
  , 'TransportArranged'
  , 'EscortRequired'
  , 'PlannedPatientTransportComment'
  , 'ProcedureCode'
  , 'ProcedureCodeModifier'
]

