exports.name = 'OBX'

exports.fields = [
    'SegmentType'
  , 'SetID'
  , 'ValueType'
  , 'ObservationIdentifier'
  , 'ObservationSubID'
  , 'ObservationValue'
  , 'Units'
  , 'ReferencesRange'
  , 'AbnormalFlags'
  , 'Probability'
  , 'NatureofAbnormalTest'
  , 'ObservationResultStatus'
  , 'DateLastObsNormalValues'
  , 'UserDefinedAccessChecks'
  , 'DateTimeoftheObservation'
  , 'ProducerID'
  , 'ResponsibleObserver'
  , 'ObservationMethod'
]
