'use strict'

exports.name = 'OBX'

exports.fields = [
    'SegmentType'
  , 'SetID'
  , 'ValueType'
  , 'ObservationIdentifier'
  , 'ObservationSubID'
  , 'ObservationValue'
  , 'Units'
  , 'ReferencesRange'
  , 'AbnormalFlags'
  , 'Probability'
  , 'NatureofAbnormalTest'
  , 'ObservationResultStatus'
  , 'EffectiveDateofReferenceRange'
  , 'UserDefinedAccessChecks'
  , 'DateTimeoftheObservation'
  , 'ProducersID'
  , 'ResponsibleObserver'
  , 'ObservationMethod'
  , 'EquipmentInstanceIdentifier'
  , 'DateTimeoftheAnalysis'
  , 'ObservationSite'
  , 'ObservationInstanceIdentifier'
  , 'MoodCode'
  , 'PerformingOrganizationName'
  , 'PerformingOrganizationAddress'
  , 'PerformingOrganizationMedicalDirector'
]
