'use strict'

exports.name = 'ORC'

exports.fields = [
    'SegmentType'
  , 'OrderControl'
  , 'PlacerOrderNumber'
  , 'FillerOrderNumber'
  , 'PlacerGroupNumber'
  , 'OrderStatus'
  , 'ResponseFlag'
  , 'QuantityTiming'
  , 'Parent'
  , 'DateTimeofTransaction'
  , 'EnteredBy'
  , 'VerifiedBy'
  , 'OrderingProvider'
  , 'EnterersLocation'
  , 'CallBackPhoneNumber'
  , 'OrderEffectiveDateTime'
  , 'OrderControlCodeReason'
  , 'EnteringOrganization'
  , 'EnteringDevice'
  , 'ActionBy'
  , 'AdvancedBeneficiaryNoticeCode'
  , 'OrderingFacilityName'
  , 'OrderingFacilityAddress'
  , 'OrderingFacilityPhoneNumber'
  , 'OrderingProviderAddress'
  , 'OrderStatusModifier'
  , 'AdvancedBeneficiaryNoticeOverrideReason'
  , 'FillersExpectedAvailabilityDateTime'
  , 'ConfidentialityCode'
  , 'OrderType'
  , 'EntererAuthorizationMode'
  , 'ParentUniversalServiceIdentifier'
]

