'use strict'

exports.name = 'PID'

exports.fields = [
    'SegmentType'
  , 'SetID'
  , 'PatientID'
  , 'PatientIdentifierList'
  , 'AlternatePatientID'
  , 'PatientName'
  , 'MothersMaidenName'
  , 'DateTimeofBirth'
  , 'AdministrativeSex'
  , 'PatientAlias'
  , 'Race'
  , 'PatientAddress'
  , 'CountyCode'
  , 'PhoneNumberHome'
  , 'PhoneNumberBusiness'
  , 'PrimaryLanguage'
  , 'MaritalStatus'
  , 'Religion'
  , 'PatientAccountNumber'
  , 'SSNNumberPatient'
  , 'DriversLicenseNumberPatient'
  , 'MothersIdentifier'
  , 'EthnicGroup'
  , 'BirthPlace'
  , 'MultipleBirthIndicator'
  , 'BirthOrder'
  , 'Citizenship'
  , 'VeteransMilitaryStatus'
  , 'Nationality'
  , 'PatientDeathDateandTime'
  , 'PatientDeathIndicator'
  , 'IdentityUnknownIndicator'
  , 'IdentityReliabilityCode'
  , 'LastUpdateDateTime'
  , 'LastUpdateFacility'
  , 'SpeciesCode'
  , 'BreedCode'
  , 'Strain'
  , 'ProductionClassCode'
  , 'TribalCitizenship'
]

