'use strict'

exports.name = 'PID'

exports.fields = [
    'SegmentType'
  , 'SetID'
  , 'PatientID'
  , 'PatientIDList'
  , 'AlternatePatientID'
  , 'PatientName'
  , 'MothersMaidenName'
  , 'DateOfBirth'
  , 'Sex'
  , 'Alias'
  , 'Race'
  , 'Address'
  , 'CountyCode'
  , 'PhoneNumberHome'
  , 'PhoneNumberBusiness'
  , 'PrimaryLanguage'
  , 'MaritalStatus'
  , 'Religion'
  , 'PatientAccountNumber'
  , 'SSN'
  , 'DriverLicenseNumber'
  , 'MothersID'
  , 'EthnicGroup'
  , 'BirthPlace'
  , 'MultipleBirthIndicator'
  , 'BirthOrder'
  , 'Citizenship'
  , 'VeteransMilitaryStatus'
  , 'Nationality'
  , 'DeathDateTime'
  , 'DeathIndicator'
]

