exports.name = 'PR1'

exports.fields = [
    'SegmentType'
  , 'SetID'
  , 'ProcedureCodingMethod'
  , 'ProcedureCode'
  , 'ProcedureDescription'
  , 'ProcedureDateTime'
  , 'ProcedureFunctionalType'
  , 'ProcedureMinutes'
  , 'Anesthesiologist'
  , 'AnesthesiaCode'
  , 'AnesthesiaMinutes'
  , 'Surgeon'
  , 'ProcedurePractitioner'
  , 'ConsentCode'
  , 'ProcedurePriority'
  , 'AssociatedDiagnosisCode'
  , 'ProcedureCodeModifier'
]
