'use strict'

exports.name = 'PV1'

exports.fields = [
    'SegmentType'
  , 'SetID'
  , 'PatientClass'
  , 'AssignedPatientLocation'
  , 'AdmissionType'
  , 'PreadmitNumber'
  , 'PriorPatientLocation'
  , 'AttendingDoctor'
  , 'ReferringDoctor'
  , 'ConsultingDoctor'
  , 'HospitalService'
  , 'TemporaryLocation'
  , 'PreadmitTestIndicator'
  , 'ReadmissionIndicator'
  , 'AdmitSource'
  , 'AmbulatoryStatus'
  , 'VIPIndicator'
  , 'AdmittingDoctor'
  , 'PatientType'
  , 'VisitNumber'
  , 'FinancialClass'
  , 'ChargePriceIndicator'
  , 'CourtesyCode'
  , 'CreditRating'
  , 'ContractCode'
  , 'ContractEffectiveDate'
  , 'ContractAmount'
  , 'ContactPeriod'
  , 'InterestCode'
  , 'TransferToBadDebtCode'
  , 'TransferToBadDebtDate'
  , 'BadDebtAgencyCode'
  , 'BadDebtTransferAmount'
  , 'BadDebtRecoveryAmount'
  , 'DeleteAccountIndicator'
  , 'DeleteAccountDate'
  , 'DischargeDisposition'
  , 'DischargedToLocation'
  , 'DietType'
  , 'ServicingFacility'
  , 'BedStatus'
  , 'AccountStatus'
  , 'PendingLocation'
  , 'PriorTemporaryLocation'
  , 'AdmitDateTime'
  , 'DischargeDateTime'
  , 'CurrentPatientBalance'
  , 'TotalCharges'
  , 'TotalAdjustments'
  , 'TotalPayments'
  , 'AlternateVisitID'
  , 'VisitIndicator'
  , 'OtherHealthcareProvider'
]

