exports.name = 'PV2'

exports.fields = [
    'SegmentType'
  , 'PriorPendingLocation'
  , 'AccommdationCode'
  , 'AdmitReason'
  , 'TransferReason'
  , 'PatientValuables'
  , 'PatientValuablesLocation'
  , 'VisitUserCode'
  , 'ExpectedAdmitDateTime'
  , 'ExpectedDischargeDateTime'
  , 'EstimatedLengthOfInpatientStay'
  , 'ActualLengthOfInpatientStay'
  , 'VisitDescription'
  , 'ReferralSourceCode'
  , 'PreviousServiceDate'
  , 'EmploymentIllnessRelatedIndicator'
  , 'PurgeStatusCode'
  , 'PurgeStatusDate'
  , 'SpecialProgramCode'
  , 'RetentionIndicator'
  , 'ExpectedNumberOfInsurancePlans'
  , 'VisitPublicityCode'
  , 'VisitProtectionIndicator'
  , 'ClinicOrganizationName'
  , 'PatientStatusCode'
  , 'VisitPriorityCode'
  , 'PreviousTreatmentDate'
  , 'ExpectedDischargeDisposition'
  , 'SignatureOnFileDate'
  , 'FirstSimilarIllnessDate'
  , 'PatientChargeAdjustmentCode'
  , 'RecurringServiceCode'
  , 'BillingMediaCode'
  , 'ExpectedSurgeryDateTime'
  , 'MilitaryPartnershipCode'
  , 'MilitaryNonAvailabilityCode'
  , 'NewbornBabyIndicator'
  , 'BabyDetainedIndicator'
]

