'use strict'

exports.name = 'RXG'

exports.fields = [
    'SegmentType'
  , 'GiveSubIDCounter'
  , 'DispenseSubIDCounter'
  , 'QuantityTiming'
  , 'GiveCode'
  , 'GiveAmountMinimum'
  , 'GiveAmountMaximum'
  , 'GiveUnits'
  , 'GiveDosageForm'
  , 'AdministrationNotes'
  , 'SubstitutionStatus'
  , 'DispenseToLocation'
  , 'NeedsHumanReview'
  , 'PharmacyTreatmentSpecialAdministraionInstructions'
  , 'GivePerTimeUnit'
  , 'GiveRateAmount'
  , 'GiveRateUnits'
  , 'GiveStrength'
  , 'GiveStrengthUnits'
  , 'SubstanceLotNumber'
  , 'SubstanceExpirationDate'
  , 'SubstanceManufacturerName'
  , 'Indication'
  , 'GiveDrugStrengthVolume'
  , 'GiveDrugStrengthVolumeUnits'
  , 'GiveBardcodeIdentifier'
  , 'PharmacyOrderType'
  , 'DispenseToPharmacy'
  , 'DispenseToPharmacyAddress'
  , 'DeliverToPatientLocation'
  , 'DeliverToAddress'
]
