'use strict'

exports.name = 'STF'

exports.fields = [
    'SegmentType'
  , 'PrimaryKeyValue'
  , 'StaffIDCode'
  , 'StaffName'
  , 'StaffType'
  , 'Sex'
  , 'DateOfBirth'
  , 'ActiveInactive'
  , 'Department'
  , 'Service'
  , 'Phone'
  , 'OfficeHomeAddress'
  , 'ActivationDate'
  , 'InactivationDate'
  , 'BackupPersonId'
  , 'EmailAddress'
  , 'PreferredMethodOfContact'
  , 'MartialStatus'
  , 'JobTitle'
  , 'JobCodeClass'
  , 'EmploymentStatus'
  , 'AdditionalInsuredOnAuto'
  , 'DriversLicenceNumber'
  , 'CopyAutoIns'
  , 'AutoInsExpires'
  , 'DateLastDMVReview'
  , 'DateNextDMVReview'
  , 'Race'
  , 'EthnicGroup'
  , 'Citizenship'
  , 'DeathDateAndTime'
  , 'DeathIndicator'
  , 'InstitutionRelationshipTypeCode'
  , 'InstitutionRelationshipPeriod'
  , 'ExpectedReturnDate'
  , 'CostCenterCode'
  , 'GenericClassificationIndicator'
  , 'InactiveReasonCode'
]
