'use strict'

exports.name = 'TXA'

exports.fields = [
    'SegmentType'
  , 'SetID'
  , 'DocumentType'
  , 'DocumentContentPresentation'
  , 'ActivityDateTime'
  , 'PrimaryActivityProviderCodeName'
  , 'OriginationDateTime'
  , 'TranscriptionDateTime'
  , 'EditDateTime'
  , 'OriginatorCodeName'
  , 'AssignedDocumentAuthenticator'
  , 'TranscriptionistCodeName'
  , 'UniqueDocumentNumber'
  , 'ParentDocumentNumber'
  , 'PlacerOrderNumber'
  , 'FillerOrderNumber'
  , 'UniqueDocumentFileName'
  , 'DocumentCompletionStatus'
  , 'DocumentConfidentialityStatus'
  , 'DocumentAvailabilityStatus'
  , 'DocumentStorageStatus'
  , 'DocumentChangeReason'
  , 'AuthenticationPersonTimestamp'
  , 'DistributedCopies'
]
